# Generated by Django 5.1.7 on 2025-03-21 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='weightcategory',
            unique_together={('min_weight', 'max_weight')},
        ),
    ]
