# Generated by Django 5.1.7 on 2025-04-11 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_alter_weightcategory_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='animalinventory',
            unique_together={('animal_type', 'breed', 'quantity')},
        ),
        migrations.RemoveField(
            model_name='birthrecord',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='birthrecord',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='birthrecord',
            name='weight_category',
        ),
        migrations.RemoveField(
            model_name='diedrecord',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='diedrecord',
            name='weight_category',
        ),
        migrations.AddField(
            model_name='birthrecord',
            name='number_of_died',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='birthrecord',
            name='number_of_female',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='birthrecord',
            name='number_of_male',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='birthrecord',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diedrecord',
            name='weight',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='animalinventory',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='animalinventory',
            name='weight_category',
        ),
    ]
