# Generated by Django 5.2 on 2025-04-18 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0004_alter_animalgroup_quantity_acquisitionrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalbreed',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='animalbreed',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/animal_breeds/'),
        ),
        migrations.AddField(
            model_name='animaltype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='animaltype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='animal_types/'),
        ),
    ]
