# Generated by Django 5.2 on 2025-04-26 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0006_acquisitionrecord_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diedrecord',
            name='status',
            field=models.CharField(blank=True, choices=[('verified', 'Verified'), ('recorded', 'Recorded'), ('cancelled', 'Cancelled')], max_length=10, null=True),
        ),
    ]
